/**
 * SYNC: mirrors dashboard/src/lib/protocol/governance-types.ts
 * SYNC: mirrors brain/src/noesis_brain/governance/types.py
 *
 * Drift detected by dashboard/test/lib/governance-types.drift.test.ts (lands in Wave 4).
 *
 * PRIVACY — VOTE-05/06 audit boundary:
 *   Proposal body text NEVER enters this file or any downstream grid module.
 *   Only title_hash (sha256(body_text)[:32]) crosses the wire.
 *   Operators are read-only at all tiers — no Vote/Propose/Reveal path.
 *   Vote-weighting keys (weight, reputation, relationship_score, ousia_weight)
 *   MUST NOT appear in any payload derived from these types.
 *
 * Per D-12-01 / D-12-02 / D-12-04 / D-12-11 / CONTEXT-12.
 *
 * Source-of-truth for GOVERNANCE_FORBIDDEN_KEYS:
 *   Declared in grid/src/audit/broadcast-allowlist.ts and re-exported here
 *   for convenience. This avoids a circular dependency (broadcast-allowlist.ts
 *   does not import governance/types.ts; governance/types.ts imports from
 *   broadcast-allowlist.ts). Dependency arrow: governance/types → broadcast-allowlist.
 *
 * No runtime side-effectful code in this file. Types and tuples only.
 * NO Date.now, NO Math.random (wall-clock ban: D-12-11 /
 * scripts/check-wallclock-forbidden.mjs TIER_B_TS_ROOTS includes grid/src/governance).
 */

// Re-export the source-of-truth GOVERNANCE_FORBIDDEN_KEYS from broadcast-allowlist.ts.
export { GOVERNANCE_FORBIDDEN_KEYS } from '../audit/broadcast-allowlist.js';

// ── proposal.opened ────────────────────────────────────────────────────────────

/**
 * Closed 6-key payload carried by the 'proposal.opened' audit event.
 * Keys are alphabetical — PROPOSAL_OPENED_KEYS enforces this order at
 * the producer boundary (appendProposalOpened.ts, Wave 2).
 *
 * PRIVACY: body text NEVER appears — only title_hash (sha256(body_text)[:32]).
 * proposal_id is a UUID v4. quorum_pct and supermajority_pct are 1..100 integers.
 * deadline_tick is the last tick for commit or reveal actions.
 * Per D-12-01 / D-12-04.
 */
export interface ProposalOpenedPayload {
    readonly deadline_tick: number;
    readonly proposal_id: string;       // UUID v4
    readonly proposer_did: string;
    readonly quorum_pct: number;        // 1..100
    readonly supermajority_pct: number; // 1..100
    readonly title_hash: string;        // sha256(body_text)[:32], lowercase hex
}

/**
 * Alphabetical tuple of ProposalOpenedPayload keys.
 * Used at the sole-producer boundary for Object.keys(payload).sort()
 * strict-equality enforcement (Phase 6 D-11 pattern).
 */
export const PROPOSAL_OPENED_KEYS = [
    'deadline_tick',
    'proposal_id',
    'proposer_did',
    'quorum_pct',
    'supermajority_pct',
    'title_hash',
] as const;

// ── ballot.committed ───────────────────────────────────────────────────────────

/**
 * Closed 3-key payload carried by the 'ballot.committed' audit event.
 * Keys are alphabetical — BALLOT_COMMITTED_KEYS enforces this order at
 * the producer boundary (appendBallotCommitted.ts, Wave 2).
 *
 * PRIVACY: commit_hash is sha256(choice|nonce|voter_did) — the preimage
 * (choice + nonce + voter_did) NEVER crosses the wire before reveal.
 * nonce is a 32 hex char string (16 bytes); generated by Brain via secrets.token_hex(16).
 * Per D-12-01 / D-12-02.
 */
export interface BallotCommittedPayload {
    readonly commit_hash: string;       // sha256 hex (64 chars) of choice|nonce|voter_did
    readonly proposal_id: string;
    readonly voter_did: string;
}

/**
 * Alphabetical tuple of BallotCommittedPayload keys.
 */
export const BALLOT_COMMITTED_KEYS = ['commit_hash', 'proposal_id', 'voter_did'] as const;

// ── ballot.revealed ────────────────────────────────────────────────────────────

/**
 * Valid ballot choices for the commit-reveal scheme (D-12-02).
 */
export type BallotChoice = 'yes' | 'no' | 'abstain';

/**
 * Closed 4-key payload carried by the 'ballot.revealed' audit event.
 * Keys are alphabetical — BALLOT_REVEALED_KEYS enforces this order at
 * the producer boundary (appendBallotRevealed.ts, Wave 2).
 *
 * At reveal time: Grid verifies sha256(choice|nonce|voter_did) === commit_hash.
 * nonce is 32 hex chars (exactly — D-12-02). Per D-12-01 / D-12-02.
 */
export interface BallotRevealedPayload {
    readonly choice: BallotChoice;
    readonly nonce: string;             // 32 hex chars (16 bytes, D-12-02)
    readonly proposal_id: string;
    readonly voter_did: string;
}

/**
 * Alphabetical tuple of BallotRevealedPayload keys.
 */
export const BALLOT_REVEALED_KEYS = ['choice', 'nonce', 'proposal_id', 'voter_did'] as const;

// ── proposal.tallied ───────────────────────────────────────────────────────────

/**
 * Outcome of a tallied proposal (D-12-03 outcome logic).
 * - 'passed'      : quorum_met AND yes_count/(yes+no) >= supermajority_pct/100
 * - 'rejected'    : quorum_met AND threshold not reached
 * - 'quorum_fail' : quorum not met (pessimistic: revealed+unrevealed_committed < quorum)
 */
export type ProposalOutcome = 'passed' | 'rejected' | 'quorum_fail';

/**
 * Closed 6-key payload carried by the 'proposal.tallied' audit event.
 * Keys are alphabetical — PROPOSAL_TALLIED_KEYS enforces this order at
 * the producer boundary (appendProposalTallied.ts, Wave 2).
 *
 * PRIVACY: individual vote choices NEVER appear — only aggregate counts.
 * abstain_count includes committed-but-not-revealed ballots for tally purposes.
 * Per D-12-01 / D-12-03 / VOTE-06.
 */
export interface ProposalTalliedPayload {
    readonly abstain_count: number;
    readonly no_count: number;
    readonly outcome: ProposalOutcome;
    readonly proposal_id: string;
    readonly quorum_met: boolean;
    readonly yes_count: number;
}

/**
 * Alphabetical tuple of ProposalTalliedPayload keys.
 */
export const PROPOSAL_TALLIED_KEYS = [
    'abstain_count',
    'no_count',
    'outcome',
    'proposal_id',
    'quorum_met',
    'yes_count',
] as const;
