"""Commit-reveal hashing for governance ballots.

SYNC: grid/src/governance/commit-reveal.ts — formula MUST be identical
Per D-12-02: commit_hash = sha256(choice + '|' + nonce + '|' + voter_did)
Pipe delimiters prevent chosen-plaintext ambiguity (e.g. 'yes_x|abc|did' vs 'yes|_xabc|did').

Phase 12 Wave 1 — VOTE-02, VOTE-03 / D-12-02 / D-12-07 / T-09-13 / T-09-14
Pure functions, stdlib only (hashlib, hmac, re, secrets). No wall-clock reads.
Wall-clock ban: datetime/time functions and random module are forbidden. D-12-11.
"""
import hashlib
import hmac
import re
import secrets
from typing import Literal

BallotChoice = Literal["yes", "no", "abstain"]

NONCE_HEX_LEN = 32  # 16 bytes hex
DID_RE = re.compile(r"^did:noesis:[a-z0-9_\-]+$", re.IGNORECASE)
CHOICE_VALUES = ("yes", "no", "abstain")


def generate_nonce() -> str:
    """Generate 32 lowercase hex chars (16 bytes) using secrets.token_hex.

    secrets.token_hex is the documented cryptographically-secure source per
    Python stdlib — it wraps os.urandom internally. NEVER substitute random.random
    or random.randint (predictable PRNG). D-12-07 / T-09-14.

    Returns:
        32-character lowercase hex string (e.g. 'a3f1...').
    """
    return secrets.token_hex(NONCE_HEX_LEN // 2)


def compute_commit_hash(choice: BallotChoice, nonce: str, voter_did: str) -> str:
    """Return sha256(choice|nonce|voter_did) as lowercase hex (64 chars).

    Formula (D-12-02): sha256(choice + '|' + nonce.lower() + '|' + voter_did)
    Pipe delimiters are load-bearing — they prevent chosen-plaintext ambiguity.
    Nonce is normalised to lowercase before hashing (uppercase-nonce invariant).

    This formula is byte-identical to grid/src/governance/commit-reveal.ts
    computeCommitHash — cross-language fixture in test_commit_hash.py proves parity.

    Args:
        choice: Ballot choice; must be one of ('yes', 'no', 'abstain').
        nonce: 32 hex chars (16 bytes) generated by generate_nonce().
        voter_did: Voter DID; must match /^did:noesis:[a-z0-9_-]+$/i.

    Returns:
        64-character lowercase hex sha256 digest.

    Raises:
        ValueError: if choice not in CHOICE_VALUES, nonce is not 32 hex chars,
                    or voter_did does not match DID_RE.
    """
    if choice not in CHOICE_VALUES:
        raise ValueError(f"commit-reveal: invalid choice {choice!r}")
    if not isinstance(nonce, str) or len(nonce) != NONCE_HEX_LEN or not re.fullmatch(r"[0-9a-fA-F]+", nonce):
        raise ValueError(f"commit-reveal: nonce must be {NONCE_HEX_LEN} hex chars")
    if not DID_RE.match(voter_did):
        raise ValueError("commit-reveal: voter_did fails DID_RE")
    payload = f"{choice}|{nonce.lower()}|{voter_did}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def verify_reveal(choice: BallotChoice, nonce: str, voter_did: str, expected_commit_hash: str) -> bool:
    """Return True iff sha256(choice|nonce|voter_did) == expected_commit_hash.

    Uses hmac.compare_digest for constant-time comparison — defence against
    timing oracles, even though commit_hash is non-secret. Matches Grid's
    XOR-loop convention and Phase 11 whisper-crypto hygiene. (T-09-13)

    Never raises on mismatch or invalid input — all error paths return False.

    Args:
        choice: Revealed ballot choice.
        nonce: 32 hex char nonce revealed by Brain.
        voter_did: The voter DID.
        expected_commit_hash: The commit_hash from the ballot.committed event.

    Returns:
        True iff the revealed (choice, nonce, voter_did) hashes to expected_commit_hash.
    """
    try:
        actual = compute_commit_hash(choice, nonce, voter_did)
    except ValueError:
        return False
    return hmac.compare_digest(actual, expected_commit_hash)
