"""
SYNC: mirrors grid/src/governance/types.ts
SYNC: mirrors dashboard/src/lib/protocol/governance-types.ts

Brain-side type mirror for the Phase 12 governance commit-reveal protocol.

Phase 12 (VOTE-01..04 / D-12-01 / D-12-02 / CONTEXT-12).

NO datetime, NO time.time, NO random — wall-clock ban per D-12-11 and
scripts/check-wallclock-forbidden.mjs (TIER_A_ROOTS includes
brain/src/noesis_brain/governance).

PRIVACY — VOTE-05/06 wire boundary:
    Proposal body text NEVER appears in this file or any derived value.
    Only title_hash (sha256(body_text)[:32], lowercase hex) crosses.
    Operators are read-only — no PROPOSE/VOTE_COMMIT/VOTE_REVEAL Brain action
    is accessible to operator code paths. D-12-11.
    Vote-weighting keys (weight, reputation, relationship_score, ousia_weight)
    MUST NOT appear in any dataclass or derived payload.

commit_hash formula (D-12-02):
    sha256(choice + '|' + nonce + '|' + voter_did)
    Pipe delimiters prevent chosen-plaintext ambiguity.
    nonce = secrets.token_hex(16) → 32 hex chars; Brain-generated, never Grid.
"""
from dataclasses import dataclass
from typing import Literal


# ── proposal.opened ────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class ProposalOpenedPayload:
    """Closed 6-key audit payload for the 'proposal.opened' event.

    Keys alphabetical — matches PROPOSAL_OPENED_KEYS tuple and
    grid/src/governance/types.ts ProposalOpenedPayload.

    PRIVACY: body text never appears — only title_hash (sha256[:32] hex).
    proposal_id is UUID v4. quorum_pct / supermajority_pct are 1..100 ints.
    """

    deadline_tick: int
    proposal_id: str       # UUID v4
    proposer_did: str
    quorum_pct: int        # 1..100
    supermajority_pct: int # 1..100
    title_hash: str        # sha256(body_text)[:32], lowercase hex


# Alphabetical tuple matching grid/src/governance/types.ts PROPOSAL_OPENED_KEYS.
# Used at the sole-producer boundary for closed-tuple enforcement.
PROPOSAL_OPENED_KEYS = (
    "deadline_tick",
    "proposal_id",
    "proposer_did",
    "quorum_pct",
    "supermajority_pct",
    "title_hash",
)


# ── ballot.committed ───────────────────────────────────────────────────────────

@dataclass(frozen=True)
class BallotCommittedPayload:
    """Closed 3-key audit payload for the 'ballot.committed' event.

    Keys alphabetical — matches BALLOT_COMMITTED_KEYS tuple.

    commit_hash = sha256(choice|nonce|voter_did) hex (64 chars). D-12-02.
    The preimage (choice + nonce) NEVER crosses the wire before reveal.
    """

    commit_hash: str       # sha256 hex (64 chars)
    proposal_id: str
    voter_did: str


BALLOT_COMMITTED_KEYS = ("commit_hash", "proposal_id", "voter_did")


# ── ballot.revealed ────────────────────────────────────────────────────────────

BallotChoice = Literal["yes", "no", "abstain"]


@dataclass(frozen=True)
class BallotRevealedPayload:
    """Closed 4-key audit payload for the 'ballot.revealed' event.

    Keys alphabetical — matches BALLOT_REVEALED_KEYS tuple.

    nonce is 32 hex chars (16 bytes); generated by Brain secrets.token_hex(16).
    Grid verifies sha256(choice|nonce|voter_did) === commit_hash at reveal.
    D-12-01 / D-12-02.
    """

    choice: BallotChoice
    nonce: str             # 32 hex chars (16 bytes)
    proposal_id: str
    voter_did: str


BALLOT_REVEALED_KEYS = ("choice", "nonce", "proposal_id", "voter_did")


# ── proposal.tallied ───────────────────────────────────────────────────────────

ProposalOutcome = Literal["passed", "rejected", "quorum_fail"]


@dataclass(frozen=True)
class ProposalTalliedPayload:
    """Closed 6-key audit payload for the 'proposal.tallied' event.

    Keys alphabetical — matches PROPOSAL_TALLIED_KEYS tuple.

    PRIVACY: individual vote choices NEVER appear — only aggregate counts.
    abstain_count includes committed-but-not-revealed ballots (pessimistic quorum).
    D-12-01 / D-12-03 / VOTE-06.
    """

    abstain_count: int
    no_count: int
    outcome: ProposalOutcome
    proposal_id: str
    quorum_met: bool
    yes_count: int


PROPOSAL_TALLIED_KEYS = (
    "abstain_count",
    "no_count",
    "outcome",
    "proposal_id",
    "quorum_met",
    "yes_count",
)


# ── Governance forbidden keys (VOTE-06 / D-12-11) ─────────────────────────────

# These keys MUST NOT appear in any governance payload on the Brain wire.
# Mirrors grid/src/audit/broadcast-allowlist.ts GOVERNANCE_FORBIDDEN_KEYS.
GOVERNANCE_FORBIDDEN_KEYS = (
    "text",
    "body",
    "content",
    "description",
    "rationale",
    "proposal_text",
    "law_text",
    "body_text",
    "weight",
    "reputation",
    "relationship_score",
    "ousia_weight",
)
