"""Reflexion — verbal self-critique stored as episodic memory (Phase 15).

Implements the Reflexion pattern from arxiv.org/abs/2303.11366:
  - After an episode with a known outcome, generate a short self-critique.
  - Store as MemoryType.REFLECTION with high importance (8.0).
  - Retrieve the 3 most recent (Ω=3) and inject into the next system prompt.

The critique is generated by calling the LLM with a structured prompt, so
it requires an LLMAdapter. If the LLM is unavailable, the reflection is
skipped silently — failure here must never block the tick loop.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Protocol

from noesis_brain.memory.sqlite_store import MemoryStore
from noesis_brain.memory.types import Memory, MemoryType

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)

# Maximum reflections kept in the active buffer (Reflexion paper recommends Ω=1–3)
REFLEXION_BUFFER_SIZE = 3


class LLMCaller(Protocol):
    """Minimal interface needed to generate a reflection text."""

    async def complete(self, system: str, user: str) -> str:
        """Return a completion string (no streaming)."""
        ...


class ReflexionBuffer:
    """Generates and stores verbal self-reflections after action episodes.

    Usage (inside BrainHandler after an episode result is known):

        buffer = ReflexionBuffer(memory_store, llm)
        await buffer.reflect(
            situation="I tried to trade but the Nous rejected me.",
            outcome="failure",
            tick=current_tick,
        )

    Then at prompt build time:
        reflections = buffer.recent(k=3)  # list[str]
    """

    def __init__(self, store: MemoryStore, llm: LLMCaller | None = None) -> None:
        self._store = store
        self._llm = llm

    # ── Write ────────────────────────────────────────────────────────────────

    async def reflect(
        self,
        situation: str,
        outcome: str,
        tick: int = 0,
        *,
        llm: LLMCaller | None = None,
    ) -> str | None:
        """Generate a self-critique for the episode and store it.

        Args:
            situation: Brief description of what happened this episode.
            outcome: "success", "failure", or a freeform short string.
            tick: Grid tick at reflection time.
            llm: Override for the LLM caller (uses constructor default if None).

        Returns:
            The generated reflection text, or None if generation failed.
        """
        caller = llm or self._llm
        if caller is None:
            logger.debug("ReflexionBuffer: no LLM available, skipping reflection")
            return None

        system = (
            "You are reflecting on your own recent behaviour. "
            "Write a single short sentence (max 200 chars) of honest self-critique "
            "that will help you do better next time. "
            "Start with 'I' and be concrete about what to change."
        )
        user = (
            f"Situation: {situation[:400]}\n"
            f"Outcome: {outcome}\n"
            "Self-reflection:"
        )

        try:
            text = await caller.complete(system, user)
        except Exception as exc:
            logger.warning("ReflexionBuffer: LLM call failed: %s", exc)
            return None

        text = text.strip()[:300]
        if not text:
            return None

        memory = Memory(
            memory_type=MemoryType.REFLECTION,
            content=text,
            importance=8.0,  # High — reflections surface above ordinary observations
            tick=tick,
        )
        self._store.add_memory(memory)
        logger.debug("ReflexionBuffer: stored reflection (tick=%d): %s", tick, text[:80])
        return text

    def store_direct(self, text: str, tick: int = 0) -> Memory:
        """Store a pre-written reflection without LLM generation.

        Useful when the Brain handler writes the reflection text itself.
        """
        text = text.strip()[:300]
        memory = Memory(
            memory_type=MemoryType.REFLECTION,
            content=text,
            importance=8.0,
            tick=tick,
        )
        return self._store.add_memory(memory)

    # ── Read ─────────────────────────────────────────────────────────────────

    def recent(self, k: int = REFLEXION_BUFFER_SIZE) -> list[str]:
        """Return the k most recent reflection texts for prompt injection."""
        memories = self._store.recent_memories(
            limit=k, memory_type=MemoryType.REFLECTION
        )
        return [m.content for m in memories]

    def recent_memories(self, k: int = REFLEXION_BUFFER_SIZE) -> list[Memory]:
        """Return the k most recent Memory objects (for full metadata access)."""
        return self._store.recent_memories(limit=k, memory_type=MemoryType.REFLECTION)
