#!/usr/bin/env bash
#
# Noēsis quickstart — bring up the whole city locally with one command.
#
# Beginner on-ramp (Q3): collapses the old ~10 manual steps into three:
#   1. install Docker + Ollama    2. run this script    3. open the browser.
#
# It checks prerequisites, pulls the local model, generates the one required
# secret into .env (idempotent), then `docker compose up` the full stack:
# MySQL + Grid + three Nous (on your local Ollama) + dashboard + steward.
#
# Usage:   ./scripts/quickstart.sh          # build + start in the background
#          ./scripts/quickstart.sh --logs   # then follow the logs
#
set -euo pipefail

MODEL="${LLM_MODEL:-qwen3:4b}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

say()  { printf '\033[36m▸ %s\033[0m\n' "$1"; }
ok()   { printf '\033[32m✓ %s\033[0m\n' "$1"; }
die()  { printf '\033[31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

# ── 1. Docker ────────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "Docker is not installed. Install Docker Desktop (docker.com) or colima, then re-run."
docker info >/dev/null 2>&1 || die "The Docker daemon is not running. Start Docker Desktop (or 'colima start'), then re-run."
ok "Docker is running"

# ── 2. Ollama + the local model ──────────────────────────────────────────────
if command -v ollama >/dev/null 2>&1; then
    if ! ollama list 2>/dev/null | grep -q "^${MODEL%%:*}"; then
        say "Pulling the local model ${MODEL} (a few GB, one time)…"
        ollama pull "$MODEL"
    fi
    ok "Ollama has ${MODEL}"
else
    printf '\033[33m! Ollama not found. Install it from https://ollama.com, then run: ollama pull %s\033[0m\n' "$MODEL"
    printf '\033[33m  The city will still start, but the Nous cannot think until Ollama serves %s.\033[0m\n' "$MODEL"
fi

# ── 3. .env with the one required secret (idempotent) ────────────────────────
if [ ! -f .env ]; then
    say "Creating .env with a generated BRAIN_HTTP_SECRET…"
    SECRET="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p | tr -d '\n')"
    {
        echo "# Generated by scripts/quickstart.sh — local development only."
        echo "BRAIN_HTTP_SECRET=${SECRET}"
        echo "DOMAIN=localhost"
        echo "MYSQL_ROOT_PASSWORD=changeme"
        echo "MYSQL_DATABASE=noesis_grid"
        echo "OLLAMA_HOST=http://host.docker.internal:11434"
        echo "LLM_MODEL=${MODEL}"
    } > .env
    ok "Wrote .env"
else
    ok ".env already exists (leaving it as-is)"
fi

# ── 4. Bring up the city ─────────────────────────────────────────────────────
say "Starting the city (docker compose up --build)… first build takes a few minutes."
docker compose up -d --build

echo
ok "Noēsis is starting."
echo "   Dashboard : http://localhost:3001"
echo "   Steward   : http://localhost:3002"
echo "   Grid API  : http://localhost:8080/health"
echo
echo "   Watch the Nous come alive:  docker compose logs -f nous-sophia"
echo "   Stop everything:            docker compose down"

if [ "${1:-}" = "--logs" ]; then
    say "Following logs (Ctrl-C to detach; the city keeps running)…"
    docker compose logs -f
fi
